name: squeak
description: "A new Flutter project to convert shared text, PDFs, ebooks, and websites into TTS audio. Find your voice."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  file_picker: ^10.1.2
  epubx: ^4.0.0
  google_mlkit_text_recognition: ^0.15.0
  read_pdf_text: ^0.3.1
  html: ^0.15.6
  http: ^1.3.0
  flutter_tts: ^4.2.2
  receive_sharing_intent: ^1.4.5
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  integration_test:
    sdk: flutter
  

flutter:
  uses-material-design: true
